bug, call: ./alpha-wrap/alpha-wrap-run drive-river

diff --git a/alpha-wrap/alpha-wrap-run b/alpha-wrap/alpha-wrap-run
--- a/alpha-wrap/alpha-wrap-run
+++ b/alpha-wrap/alpha-wrap-run
@@ -10,7 +10,7 @@
 function trace_line(){
   caller
 }
-#trap trace_line debug
+trap trace_line debug
 
 function first_arg() {
   echo $1
@@ -338,17 +338,9 @@ road
 mountain
 car"
 
-function set_create_container() {
-
-  if [ -z "$2" ]; then
-    if [ -z "${_CONTAINER_NAME}" ]; then
-      _CONTAINER_NAME="$(echo "$_VERBS" | shuf -n 1)-$(echo "$_NOUNS" | shuf -n 1)"
-    fi
-
-    _PERMANENT_CONTAINER=1
-  fi
+function get_random_name() {
+  echo "$(echo "$_VERBS" | shuf -n 1)-$(echo "$_NOUNS" | shuf -n 1)"
 }
-
 
 
 
@@ -571,6 +563,7 @@ readonly CARG_FLAG=2
 
 ARGS=$@
 CARG=
+_CARG_PARSER_ARG_REWINDED=
 
 _carg_dbg() {
   echo "DEBUG: $*"
@@ -578,6 +571,14 @@ _carg_dbg() {
 
 _carg_dbg_sink() {
   return 0
+}
+
+_errors=
+function _attach_errormsg() {
+  for msg in "$@"; do
+    _errors="$_errors
+$msg"
+  done
 }
 
 _DBG_MSG=_carg_dbg
@@ -589,19 +590,26 @@ function carg_set_param() {
   local value=$3
 
   if [ -z ${value} ]; then
-    echo "Internel error: "
-    echo "    Missing link value: $cname:$clink"
-    exit 44
+    # no thing to set
+    return 0
   fi
 
-  declare -gr "_carg_${cname}_${clink}_param=${value}"
+  # declare if value not defined, defined value is a default value
+  local param_name="_carg_${cname}_${clink}_param"
+  if [ -z ${!param_name} ]; then
+    declare -gr "${param_name}=${value}"
+  else
+    eval "${param_name}=${value}"
+  fi
 }
 
 function carg_isparam_set() {
   local cname=$1
   local clink=$2
+  local var="_carg_${cname}_${clink}_param"
 
-  [[ -v "_carg_${cname}_${clink}_param" ]] && return 0 || return 1
+  [ -n "${!var}" ]
+  return $?
 }
 
 # Return value:
@@ -645,28 +653,39 @@ function parse__MODE() {
     extstore)
       _carg_chain "MODE" $mode
     ;;
-    run|create)
-      # to be handled by 'parse_create' or 'parse_run'
+    create|run)
+      # chain to be called later
     ;;
     *)
-      return 1
+      # mode to be defined later from context
+      # it might be run or create
+      mode=
+    ;;
   esac
 
   # set value
   carg_set_param "$cname" $clink $mode
 
-  return 0
+  [ -n "$mode" ]
+  return $?
 }
 
 
 function parse__create() {
-  if [ -z $_carg_MODE ] || [ "$_carg_MODE" == "create" ]; then
+  local res=0
 
-    _carg_chain_parse "--device-d? dev_name? file_path extr_size? --imgboot-i yesno kelner? initramfs? --name-n? cont_name?" "create"
-    return $?
+  if [ ! -z $_carg__MODE_param ] && [ "$_carg__MODE_param" != "create" ]; then
+    return 1
   fi
 
-  retun 1
+  _carg_chain_parse "--device-d? dev_name? file_path extr_size? --imgboot-i yesno kelner? initramfs? --name-n? cont_name?" "create"
+  res=$?
+
+  if [ $res -eq 0 ] && [ -z $_carg__MODE_param ]; then
+    carg_set_param "" "MODE" "create"
+  fi
+
+  return $res
 }
 
 function parse_create_dev_name() {
@@ -711,8 +730,13 @@ function parse_create_file_path() {
       return 0
     fi
 
-    echo "Provide path to an existing file"
-    exit 3
+    if [ -z $__carg__MODE_param ]; then
+      # this will force to try next chain
+      return 1
+    else
+      echo "Provide path to an existing file"
+      exit 3
+    fi
   fi
 
   return 1
@@ -807,6 +831,11 @@ function parse_create_initramfs() {
   return 0
 }
 
+function validate_cont_name() {
+  [[ "$1" =~ ^([_a-zA-Z0-9-]){1,128}$ ]]
+  return $?
+}
+
 function parse_create_cont_name() {
   local cname=$1
   local clink=$2
@@ -818,7 +847,7 @@ function parse_create_cont_name() {
     return 1
   fi
 
-  if [[ ! "$name" =~ ^([_a-zA-Z0-9-]){1,128}$ ]]; then
+  if ! $(validate_cont_name); then
     echo "Illegal name"
     exit 3
   fi
@@ -826,35 +855,52 @@ function parse_create_cont_name() {
 
 
 function check_create() {
-  if  [ -n "$_carg_create_file_path_param" ] && \
-      [ -n "$_carg_create_yesno_param" ]; then
+  local err_enc=false
 
-      if ! ${_carg_create_yesno_param}; then
-        # set realpath
-        _carg_create_kelner_param=$(realpath $_carg_create_kelner_param)
-
-        if [ -n "$_carg_create_initramfs_param" ]; then
-          _carg_create_initramfs_param=$(realpath $_carg_create_initramfs_param)
-        fi
-      fi
-
-
-      return 0
+  if [ -z $_carg_create_file_path_param ]; then
+    _attach_errormsg "Provide image path" "create"
+    err_enc=true
   fi
 
-  return 1
+  if [ -z $_carg_create_yesno_param ]; then
+    _attach_errormsg "Define '--imgboot': yes|no" "create"
+    err_enc=true
+  fi
+
+  if $err_enc; then
+    return 1
+  fi
+
+  if ! ${_carg_create_yesno_param}; then
+    # set realpath
+    _carg_create_kelner_param=$(realpath $_carg_create_kelner_param)
+
+    if [ -n "$_carg_create_initramfs_param" ]; then
+      _carg_create_initramfs_param=$(realpath $_carg_create_initramfs_param)
+    fi
+  fi
+
+  # Create random name if user did not assign
+  if [ -n "$_carg_create_name_flag" ] && [ -z $parse_create_cont_name ]; then
+    parse_create_cont_name=$(get_random_name)
+    echo "Random name assigned: $parse_create_cont_name"
+  fi
+
+  return 0
 }
 
 # check main chain:
 function check_() {
 
-  if [[ -n $_carg__help_param ]] || [[ -n $_carg__help_flag ]]; then
+  if [[ -v $_carg__help_param ]] || [[ -v $_carg__help_flag ]]; then
     print_help
-  elif [[ -z $_carg_MODE ]]; then
-    echo "Nothing to do"
+  elif [ -z $_carg__MODE_param ]; then
+    echo "Wrong syntax"
     echo "    type '--help' for help"
     return 1
   fi
+
+  echo "Mode: $_carg__MODE_param"
 
   return 0
 }
@@ -876,25 +922,48 @@ function parse_extstore_MODE() {
   return 0
 }
 
+function parse__run() {
+  local res=0
+
+  if [ ! -z $_carg__MODE_param ] && [ "$_carg__MODE_param" != "run" ]; then
+    return 1
+  fi
+
+  _carg_chain_parse "--wait-w? name" "run"
+  res=$?
+
+  if [ -z $_carg__MODE_param ]; then
+    carg_set_param "" "MODE" "run"
+  fi
+
+  return $res
+}
 
 function parse_run_name() {
-  echo ""
+  local cname=$1
+  local clink=$2
+  local name=$3
+  local prev_flag=$4
+  local prev_flag_dist=$5
+
+  if ! validate_cont_name $name; then
+    _attach_errormsg "Illegal name"
+    return 1
+  fi
+
+  if [ ! -d "$DB_DIR/$name" ]; then
+    _attach_errormsg "Container does not exists"
+    return 1
+  fi
+
+  carg_set_param "$cname" $clink $name
+
+  return 0
 }
 
 
 function check_run() {
-  echo ""
-}
-
-function parse__run() {
-  if [ -z $_carg_mode ] || [ "$_carg_mode" == "run" ]; then
-    _carg_mode="run"
-
-    _carg_chain "name --wait-w?" "run"
-    return $?
-  fi
-
-  return 1
+  return 0
 }
 
 
@@ -915,6 +984,7 @@ function _carg_chain_parse() {
 
   read -a chain_arr <<< "$chain"
 
+  local link=
   local link_idx=0
   # First chain pass: scann for flags and named parameters:
   $_DBG_MSG "Loading chain: _$name"
@@ -950,8 +1020,8 @@ function _carg_chain_parse() {
         fi
 
         clflag=${tmp:2}
-        flag_conv["$cflag"]="$clflag"
-        flag_conv["$tmp"]="$cflag"
+        flag_conv[$cflag]=$clflag
+        flag_conv[$clflag]=$cflag
       else
         flag_conv[$cflag]=$cflag
         clflag=$cflag
@@ -960,9 +1030,10 @@ function _carg_chain_parse() {
       flag_subch_sidx[$cflag]=$(($link_idx+1))
       link="-$cflag"
 
-      $_DBG_MSG "      ($link_idx) adding flag: $clflag($cflag)${chain_qant[$link_idx]}"
+      $_DBG_MSG "      ($link_idx) adding flag: $clflag($cflag)${chain_qant[$link_idx]}, assoc. var.: _carg_${name}_${clflag}_flag"
+
       # it's a flag, 'param function' does not apply here:
-      chain_param_fn[$link_idx]=
+      chain_param_fn[$link_idx]=""
     else # parameter
       if declare -F parse_${name}_${link} > /dev/null; then
         chain_param_fn[$link_idx]="parse_${name}_${link}"
@@ -982,6 +1053,15 @@ function _carg_chain_parse() {
   link_cnt=${#chain_arr[@]}
   # flag_as_param
   local flag_is_flag=true
+  local tailing_cnt=
+  local arg_consumed_but_failed=false
+
+  #_CARG_PARSER_ARG_REWINDED=false
+  #if [ -z "$CARG" ]; then
+  #    # read and rewind arguments
+  #    CARG=$(first_arg ${ARGS})
+  #    ARGS=$(last_args ${ARGS})
+  #fi
 
   $_DBG_MSG "Parsing arguments: "
 
@@ -998,23 +1078,29 @@ function _carg_chain_parse() {
       ARGS=$(last_args ${ARGS})
 
       $_DBG_MSG "    Loading: $CARG"
+
+      if [ -z "$CARG" ]; then
+        # quantifier is not '?' nor '*'
+        $_DBG_MSG "      All arguments exploited, exiting _$name chain"
+
+        break
+      fi
     fi
 
     if $flag_is_flag && [[ "${CARG:0:1}" == "-" ]]; then
-      # arg_type=CARG_FLAG
       # if long form
       if [[ "${CARG:0:2}" == "--" ]]; then
         clflag=${CARG:2}
-        tmp=${flag_conv["$clflag"]}
+        tmp=${flag_conv[$clflag]}
         cflag=$tmp
       else
         cflag=${CARG:1}
-        tmp=${flag_conv["$cflag"]}
+        tmp=${flag_conv[$cflag]}
         clflag=$tmp
       fi
 
       if [ -z "$tmp" ]; then
-        $_DBG_MSG "      unidentified flag, mark 'flag_is_flag=true' to keep matching in other chains"
+        $_DBG_MSG "      unidentified flag, mark 'flag_is_flag=false' to keep matching in other chains"
         # Flag does not exists in a current chain, but it might be in other one
 
         flag_is_flag=false
@@ -1028,7 +1114,8 @@ function _carg_chain_parse() {
       tmp=$(($link_idx - 1))
       $_DBG_MSG "      identified as a flag: $clflag($cflag) ${chain_qant[$tmp]}"
       # flag exits, mark, and jump to flag specific index
-      if [[ -v $_carg_${name}_${clflag}_flag ]]; then
+      tmp="_carg_${name}_${clflag}_flag"
+      if [ ! -z ${!tmp} ]; then
         echo "Repeated flag: --$clflag (-cflag)"
         exit 3
       fi
@@ -1041,6 +1128,8 @@ function _carg_chain_parse() {
       link=${chain_arr[$link_idx]}
       qant=${chain_qant[$link_idx]}
 
+      echo "          $link_idx"
+      echo "${chain_param_fn[$link_idx]}"
       # if param is not defined, arg. is a flag
       if [ -z ${chain_param_fn[$link_idx]} ]; then
         if [ -z $qant ]; then
@@ -1055,49 +1144,23 @@ function _carg_chain_parse() {
         continue
       fi
 
-      $_DBG_MSG "    Testing arg. against parameter: $link$qant"
-      # accept empty parameter to do trought all chain links, so if
-      # something is required a proper message is shown
-      if [ -z "$CARG" ]; then
-        # quantifier is not '?' nor '*'
-        $_DBG_MSG "      All arguments exploited, exiting _$name chain"
-
-        break
-
-        #if [ -z "$qant" ]; then
-
-        #  # if not main chain,
-        #  if [ -n "$name" ]; then
-
-        #    return 1
-        #  fi
-
-        #  echo "Syntax error: "
-        #  echo "    Required parameter is missing: '$name:$link'"
-        #  exit 31
-        #fi
-
-        # rewind to the next link
-        #link_idx=$(($link_idx + 1))
-        #continue
-      fi
+      $_DBG_MSG "    Testing arg. against parameter: ${link}${qant}"
 
       if [ -n "$cflag_dist" ]; then
         cflag_dist=$(($cflag_dist + 1))
       fi
 
       $_DBG_MSG "      Calling: ${chain_param_fn[$link_idx]} \"${name}\" ${link} $CARG $cflag $cflag_dist"
+      tailing_cnt=${#ARGS}
       if ${chain_param_fn[$link_idx]} "${name}" ${link} $CARG $cflag $cflag_dist; then
-        str=_carg_${name}_${link}_param
-        tmp="${str}"
 
         if $flag_is_flag && ! $(carg_isparam_set "${name}" ${link}); then
-          echo "No return value has been set."
-          exit 8
+          $_DBG_MSG "No parameter has been set by parser, it is legal for chains"
         fi
 
         if $flag_is_flag; then
-          $_DBG_MSG "      Param variable '$str' has been set with value: '" "${tmp}" "'"
+          tmp=_carg_${name}_${link}_param
+          $_DBG_MSG "      Param variable '$tmp' has been set with value: '${!tmp}'"
         else
           $_DBG_MSG "      Flag as param. '$CARG' has been accepted by parser"
           flag_is_flag=true
@@ -1111,7 +1174,16 @@ function _carg_chain_parse() {
 
       if [ -z $qant ]; then
         echo "Missing required parameter: $link:$name"
-        exit 44
+        #exit 44
+        return 1
+      fi
+
+      # Was argument rewind?
+      if [ $tailing_cnt -ne ${#ARGS} ]; then
+        # the argument was eaten by chain that fail to parse arguments
+        # indicating wrong syntax
+        arg_consumed_but_failed=true
+        break
       fi
 
       $_DBG_MSG "      Param have not meet parser conditions, continue maching with a next link"
@@ -1120,13 +1192,23 @@ function _carg_chain_parse() {
   done
 
   if ! declare -F check_$name > /dev/null; then
-        echo "Internal error: "
-        echo "    Function 'check_$name' not defined!"
-        exit 44
+    echo "Internal error: "
+    echo "    Function 'check_$name' not defined!"
+    exit 44
   fi
 
-  check_$name
-  return $?
+  check_$name && tmp=0 || tmp=$?
+
+  if ${arg_consumed_but_failed}; then
+    tmp=1
+  fi
+
+  # if main chain and errors found
+  if [ -z $name ] && [ $tmp -ne 0 ]; then
+    echo "$_errors"
+  fi
+
+  return $tmp
 }
 
 # function, pass control to
